spring:
  application:
    name: springcloud-sample-feign

server:
  port: 8082

eureka:
  instance:
    hostname: springcloud-sample-feign
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://eureka-server:8761/eureka/

#开启熔断器
feign:
  hystrix:
    enabled: true

logging:
  level:
    com.zwh.springcloud.feign.service.ApiService: debug